### PR TITLE
Update CMakeLists.txt

### PR DESCRIPTION
**Pull request by slorello89**
Looks like something is off in the Nuspec generator yall are using - not certain if I'm keyed in on it but I think maybe because your set is going over 1 line it's dropping the whole thing?

Pretty certain: https://github.com/emgucv/emgucv/commit/84e366aba7242325f27431e92a1f3405d612b717 is what broke it essentially right now if you only install the latest emgu package you won't get all the DLL's you're binaries are linked to execute as the dependency graph is missing

Fairly certain this is causing #298 and #297 - I do not have any way of verifying on my end because I don't know what the build procedure is - if you have that handy I'd be happy to test it out.

### CODE REVIEW

**Comment by emgucv** [comment]
Thanks for contributing. 

However, the nuget package built from the existing CMake script is producing the correct dependencies, you can see that in the nuget package that has been released:
https://www.nuget.org/packages/Emgu.CV.runtime.windows/
You can click to expand the  "Dependencies" tab on the above page and the dependencies are correctly listed.

#298 is running on raspbian, we currently do not provide Emgu.CV.runtime.raspbian nuget package

#297 has been fixed in Emgu.CV.runtime.windows.4.2.0.3662 nuget package due to a missing VC runtime file.  

Using multiple line and a single line should not make a different for nuget.

For this reason, I will be denying the pull request.

**Comment by slorello89** [comment]
@emgucv 
image
The nuget projects show no dependencies for anything after 4.1.1.3497 - so I'm fairly certain something is messed up with the packaging - I tried using a cascading classifier in the latest nuget package and had the thing blow up on me before downgrading to an old version and then re-installing the latest (which brought OpenTK, OpenTK.GLControl, and ZedGraph) along with it.

**Comment by slorello89** [comment]
ok - I think I see what you mean - you can't run the Emgu.CV package you need the specific runtime - I'm assuming this is new behavior because the Emgu.CV.runtime.windows is brand new. Can I suggest instead adding a note to the original Emgu.CV NuGet package that you need to install the correct runtime environment. I know from my perspective I just looked for Emgu.CV and downloaded the first version with the most downloads - which btw works for 4.1.x

**Comment by emgucv** [comment]
It is the Emgu.CV.runtime.{platform} nuget package that has dependency on the Emgu.CV nuget pacakge.

See the 4th item on the 4.2.0 release note:
http://www.emgu.com/wiki/index.php/Version_History#Change_Log

If you have not installed the Emgu.CV.runtime.{platform} nuget packge into your project. Please do so for the 4.2.0 release. 

The line of code that you have changed are for the Emgu.CV.runtime.windows nuget package (as the name EMGUCV_WINDOWS_NUGET_DEPENDENCY indicates). The Emgu.CV.runtime.windows package clearly show the dependencies in the link below:
https://www.nuget.org/packages/Emgu.CV.runtime.windows/

**Comment by emgucv** [comment]
Yep, will work on adding a note in the original Emgu.CV nuget pacakge in the next release.

**Pull request closed without merging**
