### PR TITLE
Fix occasional error when compiling projects using the NuGet package

### LINKED ISSUE #261: Error when compiling a project which uses the NuGet package
I often get this error when compiling some projects which use the Emgu.CV NuGet package:

`Emgu.CV.targets(27,5): error : Emgu CV is not able to detect the project type, please use the pre-compiled Emgu.CV.World dll or send a bug report to support@emgu.com`

Then after some pseudo-random attempts, like unload/reaload project, the error disappears.

Unfortunately I'm not able to understand why this condition, which rises the error, sometimes is true:
`Condition="'$(EmguCvLinkTarget)'==''"`

Anyway, is there a good reason for this check?
The `EmguCvLinkTarget` property is hardcoded in the .target file, aren't all the related checks pointless?

### PR DESCRIPTION
**Pull request by paolofulgoni**
Fixes #261

### CODE REVIEW

**Comment by paolofulgoni** [comment]
@emgucv is there anything wrong with this PR?

**Comment by emgucv** [comment]
See the comments in #261 
We are not able to reproduce the bug. Can you upload a simple project that can be used to reproduce the issue?

**Comment by paolofulgoni** [comment]
Unfortunately it won't be easy, because:
* the issue shows up sometimes, but not always
* I haven't found the exact conditions which cause the issue

Let's try to see everything from another perspective: is there any reason to leave the hardcoded `EmguCvLinkTarget` property and the related Error as they are?

**Comment by emgucv** [comment]
I have posted on the original issue #261:
>I have only seem the original error message when the Emgu CV shared project is included and the shared project is not able to detect the project type to deploy the proper binary.

>I have not been able to reproduce the same error using Emgu CV nuget package reference. Can you check that when the error happens it is using the nuget package reference and the Emgu CV shared project is not used?

If it is not cause by the nuget package, we would prefer not to "fix" a bug that do not exist. 

In the unlikely even that it is caused by the nuget package, we would like to study it and avoid making the same mistake in the future. 

That's the reason we are asking for code that can reproduce the error.

**Comment by paolofulgoni** [comment]
I'll continue the discussion in the issue #261 to avoid confusion

**Comment by paolofulgoni** [comment]
Closing as the related issue is not reproducible

**Pull request closed without merging**
