### PR TITLE
Add support for CUDA 10.2, and include Maxwell GPU too

### PR DESCRIPTION
**Pull request by HEBOS**
CUDA 10.1, and 10.2 support also GPUs with capability lower than 6.0, which was lowest GPU that is specified in this script.
So, I think it is reasonable to add support for both CUDA 10.2 and support Maxwell architecture too.

### CODE REVIEW

**Comment by emgucv** [comment]
Thanks for the contribution. 

CUDA 5.0 (Maxwell) is deprecated in CUDA 10.2:
https://docs.nvidia.com/cuda/archive/10.2/cuda-toolkit-release-notes/index.html#deprecated-features

Open CV's default build setting is also set to exclude deprecated cuda_arch_bin:
https://github.com/opencv/opencv/blob/master/cmake/OpenCVDetectCUDA.cmake#L278

Emgu CV's build script is written to match the opencv official release settings. 

If needed, you can modify the build script as above to enable deprecated cuda arch. 

As the official release, we will try to keep Emgu CV match Open CV official release as much as possible. In this case, we will not be able to merge the pull request. Apologize for the inconvenient.

**Comment by HEBOS** [comment]
> 
> 
> Thanks for the contribution.
> 
> CUDA 5.0 (Maxwell) is deprecated in CUDA 10.2:
> https://docs.nvidia.com/cuda/archive/10.2/cuda-toolkit-release-notes/index.html#deprecated-features
> 
> Open CV's default build setting is also set to exclude deprecated cuda_arch_bin:
> https://github.com/opencv/opencv/blob/master/cmake/OpenCVDetectCUDA.cmake#L278
> 
> Emgu CV's build script is written to match the opencv official release settings.
> 
> If needed, you can modify the build script as above to enable deprecated cuda arch.
> 
> As the official release, we will try to keep Emgu CV match Open CV official release as much as possible. In this case, we will not be able to merge the pull request. Apologize for the inconvenient.

Is there any other build, which I can use for Maxwell 5.2, which includes windows runtime?

**Comment by emgucv** [comment]
The 4.1 release use CUDA 10.1 and have Maxwell 5.2 enabled:
https://github.com/emgucv/emgucv/blob/4.1.1/platforms/windows/Build_Binary_x86.bat#L294

**Comment by HEBOS** [comment]
> 
> 
> The 4.1 release use CUDA 10.1 and have Maxwell 5.2 enabled:
> https://github.com/emgucv/emgucv/blob/4.1.1/platforms/windows/Build_Binary_x86.bat#L294

But there is no NuGet package, right?

**Comment by emgucv** [comment]
Closing ticket now. 

Current 4.5.1 release use CUDA 11.1 and supports Maxwell 5.2. 

Instruction to download the nuget packages can be found here:
https://www.emgu.com/wiki/index.php/Version_History#Change_Log

We are not able to upload the CUDA nuget package to nuget.org because the package sizes are over nuget.org package limit of 250MB.

**Pull request closed without merging**
