### PR TITLE
Add CodeQL (#1)

### LINKED ISSUE #501: Add continuous code security analysis using GitHub CodeQL
- [CodeQL](https://github.com/github/codeql) is an open source code scanning tool for discovering vulnerabilities across a codebase

Pipeline Foundation is **a non-profit initiative** with the sole purpose of giving back to the IT community by assisting OSS projects with DevOps implementations and best practices.

Built with ❤ by [Pipeline Foundation](https://pipeline.foundation).

### PR DESCRIPTION
**Pull request by aleks-ivanov**
The pipeline:

- was extensively tested on a self-hosted Windows Server 2019 machine (because the GH-hosted machines run out of disc space during the scan) with Visual Studio 2019, .NET 5.0.202 and CMake installed
- uses [these build instructions](https://emgu.com/wiki/index.php/Download_And_Installation#Building_from_Git) for the 64-Bit variant
- works flawlessly

In addition to the main security queries, CodeQL has [extended queries](https://docs.github.com/en/code-security/secure-coding/configuring-code-scanning#running-additional-queries), which we could add to the pipeline if found useful: 
- `security-extended`, which show lower severity and precision issues 
- `security-and-quality`, which show maintainability and reliability issues. 

Resolves #501

### CODE REVIEW

**Comment by emgucv** [comment]
Looking at the detail log message at "CodeQL Analysis #1 => Analyze => Perform CodeQL Analysis" 

https://github.com/emgucv/emgucv/runs/2558752931?check_suite_focus=true

>  [2021-05-11 14:47:26] [build-stdout] [2021-05-11 14:47:26] [build-stdout] [2021-05-11 14:47:26] [WARN] Parsing error in file C:\actions-runner\_work\emgucv\emgucv\harfbuzz\docs\harfbuzz-docs.xml: Undeclared namespace prefix "xi"

It looks like codeql found the wrong project to analyze. The correct solution to analyze should be  "Solution\Windows.Desktop\Emgu.CV.sln". Or, if using dotnet 5.0 project, we can use "Emgu.CV.Example\BuildInfo.NetCore.Console" and build with "dotnet build".

Right now it is analyzing the "harfbuzz" folder, which is one of the 3rd party dependent library we build before building Emgu CV. Do you know how to fix it? Sorry, I wasn't familiar with CodeQL settings.

**Comment by aleks-ivanov** [comment]
@emgucv this is odd.

CodeQL is a bit convoluted with compiled languages and warnings like this don't necessarily point to anything of interest, because the scanner only looks at code involved in the build process after the initiation step, but we will definitely test it further and find out if there is an issue with the scan.

**Comment by aleks-ivanov** [comment]
@emgucv the following is why as far as we understand, that CodeQL scan is working properly:

1. [In this run](https://github.com/aleks-ivanov/emgucv/actions/runs/841677571) of the pipeline, we removed the step that builds the `Solution\Windows.Desktop\Emgu.CV.sln`. The result was CodeQL threw an error that it couldn't find a build process/code, therefore since CodeQL performs a successful scan when the step that builds the solution is present, we think that CodeQL properly recognizes what is being built.

2. [In this run](https://github.com/aleks-ivanov/emgucv/actions/runs/841747571) of the pipeline, we added the `security-and-quality` queries, which add a lot more rules for even the lowest severity issues and therefore usually produces a huge amount of code scanning alerts. In the case of EmguCV, this scan produced `9021 alerts` : 
123r23f3

(Side note, 4021 alerts are ignored, because the Code Scanning API has a limit of 5000 alerts returned at a time. After these 5000 are handled, on the next scan the other 4021 should be listed properly.)

The sources of those alerts as usual are almost as many as the alerts themselves, here are just a few of them:
- `Emgu.CV.Models/Dnn/VehicleLicensePlateDetector.cs`
- `Emgu.CV.Platform/DotNet/ImageBox.cs`
- `Emgu.CV/Video/BackgroundSubtractorMOG2.cs`
- `Emgu.CV/Viz/WCloud.cs`
- `Emgu.CV/Core/CvArray.cs`
- etc. etc.

This is just the first page of 200:
33g4g43g4

(Side note: many of these if not all probably come from dependencies, which is an issue  we reported awhile ago with how CodeQL doesn't have the option to ignore the dependencies of projects written in compiled languages. For that reason we usually don't implement the `security-and-quality` queries and this run is only for illustration purposes. ) 

(Side note: if you decide to use the `security-and-quality` queries, we wrote an action that executes post-CodeQL scan  and based on an array of paths dismisses existing code scanning alerts automatically in bulk i.e. if all folders with dependencies in them are declared in its config, all the alerts that stem from them would be dismissed automatically, leaving alerts from managed code.)

#

We strongly lean towards the conclusion that the `harfbuzz` folder is just **a part of the whole scan** and is included in the scan because **it is somehow connected to the build process** of the `Solution\Windows.Desktop\Emgu.CV.sln`, the way all those files and folders are included in the scan in test 2.

**Comment by emgucv** [comment]
Thanks for the explanation. Output looks great. 

We are waiting for CodeQL to confirm if our (dual licensed) software can integrate CodeQL for the build pipeline:

https://github.com/github/codeql/discussions/5886

**Comment by emgucv** [comment]
CodeQL confirms that we can integrate it into our build pipeline. Looks like we are good to go.

One question:

Our commercial releases are also based on this GitHub repository. Will you grant permission for us to use your code in both our commercial releases and open source releases?

**Comment by aleks-ivanov** [comment]
@emgucv yes absolutely, feel free to use in your commercial release, no strings attached 🙂

**Pull request merged**
